public class ActivityCodeResponseWrapper {
	public String id;
	public String numberParse;
	public String displayName;
	public String typeParse;
	public String itemCategoryId;
	public String itemCategoryCode;
	public boolean blocked;
	public String gtin;
	public Integer inventory;
	public Double unitPrice;
	public boolean priceIncludesTax;
	public Double unitCost;
	public String taxGroupId;
	public String taxGroupCode;
	public String baseUnitOfMeasureId;
	public String baseUnitOfMeasureCode;
	public String lastModifiedDateTime;
}