public class ClientD365Wrapper {
    public String id;
	public String numberParse;
	public String displayName;
	public String type;
	public String addressLine1;
	public String addressLine2;
	public String city;
	public String state;
	public String country;
	public String postalCode;
	public String phoneNumber;
	public String email;
	public String website;
	public boolean taxLiable;
	public String taxAreaId;
	public String taxAreaDisplayName;
	public String taxRegistrationNumber;
	public String currencyId;
	public String currencyCode;
	public String paymentTermsId;
	public String shipmentMethodId;
	public String paymentMethodId;
	public String blocked;
	public String lastModifiedDateTime;
}