public class VendorD365Wrapper {
	public String id;
	public String numberParse;
	public String displayName;
	public String addressLine1;
	public String addressLine2;
	public String city;
	public String state;
	public String country;
	public String postalCode;
	public String phoneNumber;
	public String email;
	public String website;
	public String taxRegistrationNumber;
	public String currencyId;
	public String currencyCode;
	public String irs1099Code;
	public String paymentTermsId;
	public String paymentMethodId;
	public boolean taxLiable;
	public String blocked;
	public Integer balance;
	public String lastModifiedDateTime;
}