name: Validate Changed Salesforce Files

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for proper diffing

      - name: Debug repository structure
        run: |
          echo "Current directory structure:"
          find . -type f | grep -iE '\.cls$|package\.xml'
          echo "Git branch info:"
          git branch -a
          echo "Git remote info:"
          git remote -v
          echo "Full diff output:"
          git diff origin/main...HEAD --name-only

      - name: Find changed Apex classes
        id: find-changes
        run: |
          # Get changed files in classes directory
          echo "Running diff command:"
          git diff origin/main...HEAD --name-only -- force-app/main/default/classes/
          
          CHANGED_CLASSES=$(git diff --name-only origin/main...HEAD -- force-app/main/default/classes/)
          echo "Raw changed classes: $CHANGED_CLASSES"
          
          # Filter for .cls files only
          CHANGED_CLASSES=$(echo "$CHANGED_CLASSES" | grep -i '\.cls$')
          echo "Filtered .cls files: $CHANGED_CLASSES"
          
          # Convert to space-separated list
          CHANGED_FILES=$(echo "$CHANGED_CLASSES" | tr '\n' ' ')
          
          # Set outputs
          echo "changed_files=${CHANGED_FILES}" >> $GITHUB_OUTPUT
          echo "has_changes=$( [ -z "$CHANGED_FILES" ] && echo 'false' || echo 'true' )" >> $GITHUB_OUTPUT
          
          echo "Final changed files output: ${CHANGED_FILES}"
          echo "Has changes output: $( [ -z "$CHANGED_FILES" ] && echo 'false' || echo 'true' )"

      # Rest of your workflow steps...
