name: Validate Changed Salesforce Files

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for proper diffing

      - name: Find changed Apex classes
        id: find-changes
        run: |
          # Fetch the base branch for comparison
          git fetch origin main
          
          # Get changed files in classes directory
          echo "Running diff command:"
          CHANGED_CLASSES=$(git diff --name-only origin/main...HEAD -- "force-app/main/default/classes/*.cls")
          echo "Changed classes: $CHANGED_CLASSES"
          
          # Convert to space-separated list
          CHANGED_FILES=$(echo "$CHANGED_CLASSES" | tr '\n' ' ' | xargs)
          
          # Set outputs
          echo "changed_files=${CHANGED_FILES}" >> $GITHUB_OUTPUT
          echo "has_changes=$( [ -z "$CHANGED_FILES" ] && echo 'false' || echo 'true' )" >> $GITHUB_OUTPUT
          
          echo "Final changed files output: ${CHANGED_FILES}"
          echo "Has changes output: $( [ -z "$CHANGED_FILES" ] && echo 'false' || echo 'true' )"

      # Rest of your workflow steps...
