name: Validate Changed Salesforce Files

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: force-app/**  # Track changes in Salesforce metadata directory

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Authenticate to Salesforce Org
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > ./auth-url.txt
          sf org login sfdx-url --sfdx-url-file ./auth-url.txt --set-default

      - name: Validate changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          # Convert space-separated list to comma-separated with proper escaping
          CHANGED_FILES=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | sed 's/ /,/g')
          
          # Add quotes if filenames contain spaces
          if [[ "$CHANGED_FILES" == *" "* ]]; then
            CHANGED_FILES="\"$CHANGED_FILES\""
          fi

          echo "Validating files: $CHANGED_FILES"
          sf project deploy validate --source-dir="$CHANGED_FILES" --wait 30 --test-level RunLocalTests --verbose
