name: Validate Changed Salesforce Files

on:
  pull_request:
    branches:
      - main  # or your default branch

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full git history for diff

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          base_sha: ${{ github.event.pull_request.base.sha }}
          sha: ${{ github.event.pull_request.head.sha }}
          files: |
            force-app/**
            manifest/**
            sfdx-project.json

      - name: List changed files
        run: |
          echo "All changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
          echo "Modified files: ${{ steps.changed-files.outputs.modified_files }}"
          echo "Added files: ${{ steps.changed-files.outputs.added_files }}"

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli
          sf --version

      - name: Authenticate to Salesforce Org
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > ./auth-url.txt
          sf org login sfdx-url --sfdx-url-file ./auth-url.txt --set-default --alias validation-org

      - name: Validate deployment of changed files
  if: steps.changed-files.outputs.any_changed == 'true'
  run: |
    # Convert newline-separated list to comma-separated
    CHANGED_FILES=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr '\n' ',')
    echo "Validating files: $CHANGED_FILES"
    sf project deploy validate \
      --metadata "$CHANGED_FILES" \
      --wait 30 \
      --test-level RunLocalTests \
      --verbose
