name: Validate Salesforce Deployment

on:
  pull_request:
    branches:
      - main  # Run validation when PR targets main branch

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Authenticate to Salesforce Org
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > ./auth-url.txt
          sf org login sfdx-url --sfdx-url-file ./auth-url.txt --set-default

      - name: Validate deployment in Salesforce Org
        run: |
          sf project deploy validate --source-dir force-app --wait 30 --test-level RunLocalTests --verbose
