name: Validate Changed Salesforce Files

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for proper git diff

      - name: Get changed component folders
        id: changed-folders
        run: |
          # Get unique parent directories for changed files
          CHANGED_DIRS=$(git diff --name-only origin/main...HEAD 'force-app/main/default/lwc/' | xargs -n1 dirname | sort -u | tr '\n' ',' | sed 's/,$//')
          echo "changed_folders=$CHANGED_DIRS" >> $GITHUB_OUTPUT

      - name: List changed folders
        run: |
          echo "Changed component folders:"
          echo "${{ steps.changed-folders.outputs.changed_folders }}"

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Authenticate to Salesforce Org
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > ./auth-url.txt
          sf org login sfdx-url --sfdx-url-file ./auth-url.txt --set-default

      - name: Validate changed components
        if: steps.changed-folders.outputs.changed_folders != ''
        run: |
          echo "Validating: ${{ steps.changed-folders.outputs.changed_folders }}"
          sf project deploy validate --source-dir "${{ steps.changed-folders.outputs.changed_folders }}" --wait 30 --test-level RunLocalTests --verbose

      - name: Skip if no components changed
        if: steps.changed-folders.outputs.changed_folders == ''
        run: echo "No components changed. Skipping validation."
